name: nedas
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.11.10
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024b
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - certifi==2024.8.30
      - cftime==1.6.4.post1
      - contourpy==1.3.1
      - cycler==0.12.1
      - fonttools==4.55.1
      - kiwisolver==1.4.7
      - llvmlite==0.43.0
      - matplotlib==3.9.3
      #- mpi4py==4.0.1        ##this is optional, will require the MPI library
      - netcdf4==1.7.2
      #- numba==0.60.0        ##this is optional
      - numpy==2.0.2
      - packaging==24.2
      - pillow==11.0.0
      #- pyfftw==0.15.0       ##this is optional, requires FFTW
      - pyparsing==3.2.0
      - pyproj==3.7.0
      - pyshp==2.3.1
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.2
      - scipy==1.14.1
      - six==1.16.0
