#&time_control
run_days: 0
run_hours: 36
run_minutes: 0
run_seconds: 0
start_year: 2019
start_month: 09
start_day: 04
start_hour: 12
end_year: 2019
end_month: 09
end_day: 06
end_hour: 00
interval_seconds: 10800
input_from_file: True
history_interval: 60
frames_per_outfile: 1
restart: False
restart_interval: 7200
io_form_history: 2
io_form_restart: 2
io_form_input: 2
io_form_boundary: 2

#&domains
time_step: 90
time_step_fract_num: 0
time_step_fract_den: 1
max_dom: 2
e_we: 150
e_sn: 130
e_vert: 45
dzstretch_s: 1.1
p_top_requested: 5000
num_metgrid_levels: 34
num_metgrid_soil_levels: 4
dx: 15000
dy: 15000
grid_id: 1
parent_id: 0
i_parent_start: 1
j_parent_start: 1
parent_grid_ratio: 1
parent_time_step_ratio: 1
feedback: 1
smooth_option: 0

#&physics
physics_suite: 'CONUS'
mp_physics: -1
cu_physics: -1
ra_lw_physics: -1
ra_sw_physics: -1
bl_pbl_physics: -1
sf_sfclay_physics: -1
sf_surface_physics: -1
radt: 15
bldt: 0
cudt: 0
icloud: 1
num_land_cat: 21
sf_urban_physics: 0
fractional_seaice: 1

#&dynamics
hybrid_opt: 2
w_damping: 0
diff_opt: 2
km_opt: 4
diff_6th_opt: 0
diff_6th_factor: 0.12
base_temp: 290.
damp_opt: 3
zdamp: 5000.
dampcoef: 0.2
khdif: 0
kvdif: 0
non_hydrostatic: True
moist_adv_opt: 1
scalar_adv_opt: 1
gwd_opt: 1

#&bdy_control
spec_bdy_width: 5
specified: True

#&namelist_quilt
nio_tasks_per_group: 0
nio_groups: 1



