#&time_control
interval_seconds: 10800
input_from_file: [True]
history_interval: [60]
frames_per_outfile: [1]
restart: False
restart_interval: 720
io_form_geogrid: 2
geog_data_path: '/cluster/work/users/yingyue/data/GEOG/'
geog_data_res: '5m'
io_form_metgrid: 2
io_form_history: 2
io_form_restart: 2
io_form_input: 2
io_form_boundary: 2

#&domains
time_step: 90
time_step_fract_num: 0
time_step_fract_den: 1
max_dom: 1
map_proj: 'polar'
ref_lat: 90.0
ref_lon: -45.0
truelat1: 60.0
truelat2: 70.0
stand_lon: -45.0
e_we: [600]
e_sn: [600]
e_vert: [72]
dzstretch_s: 1.1
p_top_requested: 300
num_metgrid_levels: 38
num_metgrid_soil_levels: 4
dx: [10000]
dy: [10000]
grid_id: [1]
parent_id: [0]
i_parent_start: [1]
j_parent_start: [1]
parent_grid_ratio: [1]
parent_time_step_ratio: [1]
feedback: 1
smooth_option: 2

#&physics
mp_physics: [1]
cu_physics: [1]
ra_lw_physics: [1]
ra_sw_physics: [1]
bl_pbl_physics: [1]
sf_sfclay_physics: [1]
sf_surface_physics: [1]
radt: [15]
bldt: [0]
cudt: [5]
icloud: 1
num_land_cat: 21
sf_urban_physics: [0]
seaice_thickness_opt: 0
seaice_thickness_default: 1.0
seaice_albedo_opt: 0
seaice_albedo_default: 0.8
seaice_snowdepth_opt: 0
seaice_snowdepth_min: 0.002
seaice_snowdepth_max: 0.05
fractional_seaice: 1
surface_input_source: 1
ysu_topdown_pblmix: 0

#&dynamics
hybrid_opt: 0
etac: 0
w_damping: 1
diff_opt: [1]
km_opt: [4]
diff_6th_opt: [0]
diff_6th_factor: [0.12]
base_temp: 290.
damp_opt: 0
zdamp: [5000.]
dampcoef: [0.2]
khdif: [0]
kvdif: [0]
non_hydrostatic: [True]
moist_adv_opt: [1]
scalar_adv_opt: [1]
gwd_opt: [0]
use_theta_m: 0

#&bdy_control
specified: True
spec_bdy_width: 10

#&namelist_quilt
nio_tasks_per_group: 0
nio_groups: 1

debug_level: 1

