work_dir: /work

job_submit:
  host: docker
  ppn: 16
  run_separate_jobs: False

nproc: 5

nens: 20
run_forecast: True
run_analysis: True
run_diagnose: True
debug: False

time_start: 2001-01-01T00:00:00Z
time_end: 2001-01-14T00:00:00Z
time_analysis_start: 2001-01-03T00:00:00Z
time_analysis_end: 2001-01-09T00:00:00Z
cycle_period: 24

obs_time_steps: [0]
obs_time_scale: 0
state_time_steps: [0]
state_time_scale: 0

grid_def:
  type: qg

state_def:
- name: streamfunc
  model_src: qg
  var_type: field
  err_type: normal

model_def:
  qg:
    config_file: /app/NEDAS/NEDAS/models/qg/default.yml
    model_code_dir: /app/NEDAS/NEDAS/models/qg
    model_env: /app/setup_docker.src
    ens_run_type: scheduler
    ens_init_dir: /work/init_ens
    truth_dir: /work/truth

obs_def:
- name: streamfunc
  dataset_src: qg
  model_src: qg
  nobs: 3000
  err:
    type: normal
    std: 0.2
  hroi: 100
  vroi: inf
  troi: inf

use_synthetic_obs: True

dataset_def:
  qg:
    obs_window_min: -6
    obs_window_max: 0

perturb:

analysis_scheme: offline_filter

niter: 1
iter: 0

assimilator_def:
  type: etkf

updator_def:
  type: additive

covariance_def:
  type: ensemble

inflation_def:
  type: posterior,rtpp
  adaptive: True
  coef: 1.0

localization_def:
  horizontal: GC
  vertical: GC
  temporal: exp

transform_def:
- type: scale_bandpass
  decompose_obs: False
resolution_level: [0]
character_length: [10]
localize_scale_fac: [1]
obs_err_scale_fac: [1]

diag:
- method: misc.convert_output
  config_file: /app/NEDAS/NEDAS/diag/misc/convert_output/default.yml
  model_src: qg
  variables: ['streamfunc', 'temperature', 'vorticity']
  grid_def:
  file: '/work/output/mem{member:03}_b{time:%Y-%m-%d}T{time:%H}.nc'
