work_dir: '/cluster/work/users/yingyue/qg.emulator'   ##working directory for the experiment

job_submit:

nproc: 1          ##total number of processors

nens: 100         ##ensemble size
run_forecast: True
run_analysis: True   ##if true, run the assimilation steps
run_diagnose: False
debug: False      ##if true, output debug data/message

time_start: '202301010000'       ##start time of the experiment, format ccyymmddHHMM
time_end: '202302180000'         ##end time of the experiment
time_analysis_start: '202301010000' ##start time of the first analysis cycle
time_analysis_end: '202302180000'   ##end time of the last analysis cycle
cycle_period: 12                 ##cycle period, in hours

obs_time_steps: [0]
obs_time_scale: 0
state_time_steps: [0]
state_time_scale: 0

grid_def:
  type: 'qg.emulator'

state_def:
- name: 'streamfunc'
  model_src: 'qg.emulator'
  var_type: 'field'
  err_type: 'normal'

obs_def:
- name: 'streamfunc'
  dataset_src: 'qg'
  model_src: 'qg.emulator'
  nobs: 3000
  err:
    type: 'normal'
    std: 0.2
  hroi: 100
  vroi: 5
  troi: 24
  impact_on_state:
     streamfunc: 1.0

dataset_def:
  qg:
    obs_window_min: -6
    obs_window_max: 0

use_synthetic_obs: True

model_def:
  qg.emulator:
    config_file: '/cluster/home/yingyue/code/NEDAS/models/qg/emulator/default.yml'
    nproc_per_run: 1    ##number of processors to run a forecast
    ens_run_type: batch
    ens_init_dir: '/cluster/work/users/yingyue/qg_ens_runs'
    truth_dir: '/cluster/work/users/yingyue/qg/truth'

perturb:

assim_mode: 'serial'
filter_type: 'EAKF'

inflation:
  type: 'posterior,relax'
  adaptive: True
  coef: 1.0

localization:
  horizontal: 'GC'
  vertical: 'GC'
  temporal: 'exp'

diag: