dataset_dir: '/cluster/projects/nn2993k/sim/data/OSISAF_ice_drift'

##osisaf grid parameters
proj_name: 'nh_polstere'
proj: '+proj=stere +a=6378273 +b=6356889.44891 +lat_0=90 +lat_ts=70 +lon_0=-45'
xstart: -3845000.
xend: 3755000.
dx: 10000.
ystart: 5845000.
yend: -5355000.
dy: -10000.

