dataset_dir:
obs_file_dt: 24
obs_days: 7
use_dataset_uncertainty: False

##osisaf grid parameters
proj: "+proj=laea +lon_0=0 +datum=WGS84 +ellps=WGS84 +lat_0=90.0"
xstart: -5387500.
xend: 5388000.
dx: 25000.
ystart: 5387500.
yend: -5388000.
dy: -25000.