# model nondimensional parameters
nx: 40   # model dimension
F: 8     # forcing parameter
F_std: 0 # std for per-member F perturbation (0 = no SSPE)
dt: 0.05 # time step

numeric_opt: rk4

# some dimensional parameters
restart_dt: 24  # restart interval (hours)
nproc_per_run: 1
nproc_per_util: 1
walltime: 10

ens_init_dir:
truth_dir:
