work_dir: '/cluster/work/users/yingyue/nextsim_test'   ##working directory for the experiment
job_submit:
  host: betzy
  scheduler: slurm
  ppn: 128
  project: nn2993k
  queue: normal
  run_separate_jobs: False
  use_job_array: False

nproc: 128        ##total number of processors

nens: 20         ##ensemble size
run_forecast: True
run_analysis: True  ##if true, run the assimilation steps
run_diagnose: False

debug: False     ##if true, output debug data/message

time_start: '200612220000'       ##start time of the experiment, format ccyymmddHHMM
time_end: '200702150000'         ##end time of the experiment
time_analysis_start: '200701010000' ##start time of the first analysis cycle
time_analysis_end: '200702140000'   ##end time of the last analysis cycle
cycle_period: 24                 ##cycle period, in hours

obs_time_steps: [0]
obs_time_scale: 0
state_time_steps: [0]
state_time_scale: 0

grid_def:
  type: 'custom'
  proj: '+proj=stere +a=6378273 +b=6356889.448910593 +lat_0=90 +lon_0=-45 +lat_ts=60'
  xmin: -2.5e6
  xmax: 2.498e6
  ymin: -2e6
  ymax: 2.5e6
  dx: 3e3
  centered: True

state_def:
- name: 'seaice_conc'
  model_src: 'nextsim.v1'
  var_type: 'field'
  err_type: 'normal'
- name: 'seaice_thick'
  model_src: 'nextsim.v1'
  var_type: 'field'
  err_type: 'normal'
- name: 'seaice_velocity'
  model_src: 'nextsim.v1'
  var_type: 'field'
  err_type: 'normal'

obs_def:
- name: 'seaice_conc'
  dataset_src: 'osisaf'
  dataset_dir: '/cluster/work/users/yingyue/data/osisaf'
  model_src: 'nextsim.v1'
  obs_window_min: -6
  obs_window_max: 0
  err:
    type: 'normal'
    std: 0.2
  hroi: 1e5
  vroi: 1e10
  troi: 24
  impact_on_state:
    seaice_velocity: 0.5

use_synthetic_obs: False

model_def:
  nextsim.v1:
    config_file: '/cluster/home/yingyue/code/NEDAS/models/nextsim/v1/default.yml'
    model_env: '/cluster/home/yingyue/code/NEDAS/models/nextsim/v1/env/setup_fram.src'
    nextsim_dir: '/cluster/home/yingyue/code/nextsim'
    nextsim_mesh_dir: '/cluster/projects/nn2993k/sim/mesh'
    nextsim_data_dir: '/cluster/projects/nn2993k/yingyue/data'
    atmos_forcing_path: 'GENERIC_PS_ATM'
    ocean_forcing_path: 'TOPAZ4_reanalysis-merged'
    nproc_per_run: 32
    walltime: 10000
    restart_dt: 6
    forcing_dt: 6
    ens_run_type: scheduler
    ens_init_dir: '/cluster/projects/nn2993k/yingyue/nextsim_ens_runs/control'
    truth_dir: ''

perturb:
- variable: ['atmos_surf_press', 'atmos_surf_velocity']
  model_src: 'nextsim.v1'
  type: 'gaussian,press_wind_relate,scale_wind'
  amp: [50, 1]
  hcorr: [2e5, 2e5]
  tcorr: [72, 72]
#- variable: 'seaice_conc'
#  model_src: 'nextsim.v1'
#  type: 'displace'
#  amp: 3e4
#  hcorr: 2e5
#  tcorr: 72

assim_mode: 'serial'
filter_type: 'EAKF'

inflation:
  type: 'posterior,relax'
  adaptive: True
  coef: 1.0

localization:
  htype: 'GC'
  vtype: 'GC'
  ttype: 'GC'

