work_dir: '/cluster/work/users/yingyue/qg'   ##working directory for the experiment

job_submit:
  ppn: 16

nproc: 5        ##total number of processors

nens: 20         ##ensemble size
run_forecast: True
run_analysis: True  ##if true, run the assimilation steps
run_diagnose: True
debug: False      ##if true, output debug data/message

time_start: '202301010000'       ##start time of the experiment, format ccyymmddHHMM
time_end: '202302180000'         ##end time of the experiment
time_analysis_start: '202301010000' ##start time of the first analysis cycle
time_analysis_end: '202302180000'   ##end time of the last analysis cycle
cycle_period: 12                 ##cycle period, in hours

obs_time_steps: [0]
obs_time_scale: 0
state_time_steps: [0]
state_time_scale: 0

grid_def:
  type: 'qg'

state_def:
- name: 'streamfunc'
  model_src: 'qg'
  var_type: 'field'
  err_type: 'normal'

obs_def:
- name: 'streamfunc'
  dataset_src: 'qg'
  model_src: 'qg'
  obs_window_min: -6
  obs_window_max: 0
  nobs: 3000
  err:
    type: 'normal'
    std: 0.2
  hroi: 100
  vroi: 5
  troi: 24
  impact_on_state:
    streamfunc: 1.0

use_synthetic_obs: True

dataset_def:
  qg:

model_def:
  qg:
    config_file: '/cluster/home/yingyue/code/NEDAS/models/qg/default.yml'
    model_code_dir: '/cluster/home/yingyue/code/NEDAS/models/qg'
    model_env: '/cluster/home/yingyue/code/NEDAS/models/qg/env/setup_betzy.src'
    ens_run_type: scheduler
    ens_init_dir: '/cluster/work/users/yingyue/qg_ens_runs'
    truth_dir: '/cluster/work/users/yingyue/qg/truth'

perturb:

assim_mode: 'batch'
filter_type: 'ETKF'

##multiscale approach
nscale: 1                    ## number of scale components
scale_id: 0                  ## current scale index
decompose_obs: False         ## if true, decompose observations as well
character_length: [150, 50, 10]   ## characteristic length (in grid coord unit) for each scale (large to small)
localize_scale_fac: [1, 1, 1]   ## scale factor for localization distances
obs_err_scale_fac: [1, 1, 1]    ## scale factor for observation error variances

run_alignment: False  ## if true, run alignment technique
alignment:
  option: 'optical_flow'     ## which alignment algorithm to use
  variable: 'streamfunc'     ## which variable the alignment is based on
  nlevel: 5                  ## number of resolution levels used in pyramid method
  smoothness_weight: 1       ## strength of the smoothness constraint

inflation:
  type: 'posterior,relax'
  adaptive: True
  coef: 1.0

localization:
  htype: 'GC'
  vtype: 'GC'
  ttype: 'GC'

diag:
- method: 'misc.convert_output'
  is_ensemble: False
  config_file: '/cluster/home/yingyue/code/NEDAS/diag/misc/convert_output/default.yml'
  model_src: 'qg'
  variables: ['streamfunc', 'temperature', 'vorticity']
  grid_def:
  file: '/cluster/work/users/yingyue/qg/output/mem{member:03}_b{time:%Y-%m-%d}T{time:%H}.nc'
