work_dir: '/cluster/work/users/yingyue/TP5'   ##working directory for the experiment

python_env: '/cluster/home/yingyue/python.src'   ##python environment source script

job_submit:
  host: betzy
  project: nn2993k
  queue: normal
  scheduler: slurm
  ppn: 128
  run_separate_jobs: True

nproc: 512      ##total number of processors for assimilate

nens: 10         ##ensemble size
run_forecast: True
run_analysis: False ##if true, run the assimilation steps
run_diagnose: True
debug: False     ##if true, output debug data/message

time_start: '202107010000'       ##start time of the experiment, format ccyymmddHHMM
time_end: '202107100000'         ##end time of the experiment
time_analysis_start: '202107010000' ##start time of the first analysis cycle
time_analysis_end: '202107100000'   ##end time of the last analysis cycle
cycle_period: 168                 ##cycle period, in hours

time: '202107010000'

obs_time_steps: [0]
obs_time_scale: 0
state_time_steps: [0]
state_time_scale: 0

grid_def:
  type: 'topaz.v5'

state_def:
- name: 'ocean_velocity'
  model_src: 'topaz.v5'
  var_type: 'field'
  err_type: 'normal'
- name: 'ocean_temp'
  model_src: 'topaz.v5'
  var_type: 'field'
  err_type: 'normal'
- name: 'ocean_saln'
  model_src: 'topaz.v5'
  var_type: 'field'
  err_type: 'normal'
- name: 'ocean_layer_thick'
  model_src: 'topaz.v5'
  var_type: 'field'
  err_type: 'normal'
- name: 'ocean_mixl_depth'
  model_src: 'topaz.v5'
  var_type: 'field'
  err_type: 'normal'
- name: 'ocean_b_velocity'
  model_src: 'topaz.v5'
  var_type: 'field'
  err_type: 'normal'
- name: 'ocean_b_press'
  model_src: 'topaz.v5'
  var_type: 'field'
  err_type: 'normal'
- name: 'seaice_velocity'
  model_src: 'topaz.v5'
  var_type: 'field'
  err_type: 'normal'
- name: 'seaice_conc'
  model_src: 'topaz.v5'
  var_type: 'field'
  err_type: 'normal'
- name: 'seaice_thick'
  model_src: 'topaz.v5'
  var_type: 'field'
  err_type: 'normal'

obs_def:
- name: 'ocean_temp'
  dataset_src: 'topaz'
  model_src: 'topaz.v5'
  hroi: 2e5
  vroi: inf
  troi: inf
  impact_on_state:
- name: 'ocean_saln'
  dataset_src: 'topaz'
  model_src: 'topaz.v5'
  hroi: 2e5
  vroi: inf
  troi: inf
  impact_on_state:
- name: 'ocean_surf_temp'
  dataset_src: 'topaz'
  model_src: 'topaz.v5'
  hroi: 2e5
  vroi: inf
  troi: inf
  impact_on_state:
- name: 'ocean_surf_height_anomaly'
  dataset_src: 'topaz'
  model_src: 'topaz.v5'
  hroi: 2e5
  vroi: inf
  troi: inf
  impact_on_state:
- name: 'seaice_conc'
  dataset_src: 'topaz'
  model_src: 'topaz.v5'
  hroi: 2e5
  vroi: 100
  troi: inf
  impact_on_state:
- name: 'seaice_thick'
  dataset_src: 'topaz'
  model_src: 'topaz.v5'
  hroi: 2e5
  vroi: 100
  troi: inf
  impact_on_state:
- name: 'seaice_drift'
  dataset_src: 'topaz'
  model_src: 'topaz.v5'
  hroi: 2e5
  vroi: 100
  troi: inf
  impact_on_state:

use_synthetic_obs: False

dataset_def:
  topaz:
    config_file: '/cluster/home/yingyue/code/NEDAS/dataset/topaz/default.yml'

model_def:
  topaz.v5:
    config_file: '/cluster/home/yingyue/code/NEDAS/models/topaz/v5/default.yml'
    basedir: '/cluster/work/users/yingyue/TP5a0.06'
    model_env: '/cluster/home/yingyue/code/NEDAS/models/topaz/env/setup.src'
    nproc: 511
    nproc_per_run: 512  ##nproc for model.run
    nproc_per_util: 1   ##nproc for other utility funcs, model.preprocess etc.
    walltime: 3600     ##walltime in seconds
    restart_dt: 168
    forcing_dt: 6
    ens_run_type: scheduler
    use_job_array: False
    stagnant_log_timeout: 100
    ens_init_dir: '/cluster/work/users/yingyue/26111/FORECAST'
    forcing_file: '/cluster/work/users/yingyue/TP5a0.06/force/synoptic/041/{name}'
    truth_dir: ''

perturb:
- variable: ['atmos_surf_press', 'atmos_surf_velocity']
  model_src: 'topaz.v5'
  type: 'gaussian,press_wind_relate,scale_wind'
  amp: [316., 1.58]
  hcorr: [2.5e5, 2.5e5]
  tcorr: [48, 48]
- variable: 'atmos_surf_temp'
  model_src: 'topaz.v5'
  type: 'gaussian'
  amp: 2
  hcorr: 2.5e5
  tcorr: 48
- variable: 'atmos_precip'
  model_src: 'topaz.v5'
  type: 'gaussian,exp'
  amp: 0.5
  hcorr: 2.5e5
  tcorr: 48
  bounds: [0, inf]
- variable: 'atmos_down_longwave'
  model_src: 'topaz.v5'
  type: 'gaussian,exp'
  amp: 0.045
  hcorr: 2.5e5
  tcorr: 48
- variable: 'atmos_down_shortwave'
  model_src: 'topaz.v5'
  type: 'gaussian,exp'
  amp: 0.045
  hcorr: 2.5e5
  tcorr: 48

assim_mode: 'batch'
filter_type: 'ETKF'
rfactor: 2.0
kfactor: 2.0
nlobs_max: 3000

covariance:
  type: 'ensemble'
  #hybrid_weight: 0.5
  #static_lookup_table: '/cluster/home/yingyue/data/cov/static.yml'

inflation:
  type: 'posterior,inflate'
  adaptive: False
  coef: 1.01

localization:
  htype: 'GC'
  vtype: 'GC'
  ttype: 'GC'
  #NICE_lookup_table: '/cluster/work/users/yingyue/NICE/lookup.{nens}.mat'

diag:
##convert seaice conc output to nc files for ICECAP diagnostics
- method: 'misc.convert_output'
  config_file: '/cluster/home/yingyue/code/NEDAS/diag/misc/convert_output/default.yml'
  model_src: 'topaz.v5'
  dt_hours: 24
  variables: ['seaice_conc_daily']
  file: '/cluster/work/users/yingyue/TP5/output/{time:%Y}/{time:%m}/topaz5_local_mem{member:03}_b{time:%Y-%m-%d}T{time:%H}.nc'

##plot state variables for ensemble viewer
- method: 'plot.ensemble_states'
  variables: ['ocean_temp', 'ocean_saln', 'ocean_velocity', 'ocean_layer_thick', 'ocean_surf_height', 'seaice_velocity_daily', 'seaice_conc_daily', 'seaice_thick_daily', 'seaice_conc_ncat', 'seaice_volume_ncat', 'atmos_surf_velocity', 'atmos_surf_temp', 'atmos_surf_press', 'atmos_precip']
  model_src: ['topaz.v5', 'topaz.v5', 'topaz.v5', 'topaz.v5', 'topaz.v5', 'topaz.v5', 'topaz.v5', 'topaz.v5', 'topaz.v5', 'topaz.v5', 'topaz.v5', 'topaz.v5', 'topaz.v5', 'topaz.v5']
  vmin: [-10,  4, -0.1,   0, -1, -0.1, 0, 0, 0, 0, -10, -20,  98000,    0]
  vmax: [ 20, 38,  0.1, 1e7,  1,  0.1, 1, 5, 1, 3,  10,  35, 104500, 2e-6]
  nlevels: [15, 17, 10,  20, 20,  10, 10, 10,10,15, 10,  11,     10,   10]
  cmap: ['cmocean.thermal', 'cmocean.haline', 'bwr', 'cmocean.dense', 'cmocean.balance', 'bwr', 'cmocean.ice', 'viridis', 'Reds', 'Reds', 'bwr', 'cmocean.thermal', 'cmocean.dense', 'cmocean.rain']

- method: 'plot.observations'
  obs_window_min: -168
  obs_window_max: 0
  variables: ['ocean_temp', 'ocean_saln', 'ocean_surf_temp', 'seaice_conc', 'seaice_thick', 'seaice_drift']
  dataset_src: ['topaz', 'topaz', 'topaz', 'topaz', 'topaz', 'topaz']
  obs_dt: [168, 168, 168, 168, 168, 24]
  obs_kmin: [ 1,  1,  0, 0, 0, 0]
  obs_kmax: [50, 50,  0, 0, 0, 0]
  vmin: [-10,  4, -10,  0, 0, -50]
  vmax: [ 20, 38,  20,  1, 5,  50]
  nlevels: [15,17, 15, 10,10,  10]
  cmap: ['cmocean.thermal', 'cmocean.haline', 'cmocean.thermal', 'cmocean.ice', 'viridis', 'bwr']
  vmin_diff: [-5, -10, -5, -0.5, -2, -50]
  vmax_diff: [ 5,  10,  5,  0.5,  2,  50]
  nlevels_diff: [10, 10, 10, 10, 10, 10]
  cmap_diff: ['cmocean.balance', 'cmocean.balance', 'cmocean.balance', 'cmocean.balance', 'cmocean.balance', 'cmocean.balance']

- method: 'plot.analysis_increments'
  variables: ['ocean_temp', 'ocean_saln', 'ocean_velocity', 'ocean_layer_thick', 'seaice_conc_ncat', 'seaice_volume_ncat']
  vmin_diff: [-5, -10, -0.1, -1e5, -0.5, -2]
  vmax_diff: [ 5,  10,  0.1,  1e5,  0.5,  2]
  nlevels_diff: [10, 10, 10, 10, 10, 10]
  cmap_diff: ['cmocean.balance', 'cmocean.balance', 'cmocean.balance', 'cmocean.balance', 'cmocean.balance', 'cmocean.balance']

