work_dir: '/cluster/work/users/yingyue/TP5_test'   ##working directory for the experiment

python_env: '/cluster/home/yingyue/python.src'   ##python environment source script

job_submit:
  host: betzy
  project: nn2993k
  queue: normal
  scheduler: slurm
  ppn: 128
  run_separate_jobs: True

nproc: 512       ##total number of processors for assimilate

nens: 10         ##ensemble size
run_assim: False ##if true, run the assimilation steps
run_diag: True
debug: False     ##if true, output debug data/message

time_start: '202107120000'       ##start time of the experiment, format ccyymmddHHMM
time_end: '202108030000'         ##end time of the experiment
time_assim_start: '202107130000' ##start time of the first analysis cycle
time_assim_end: '202107300000'   ##end time of the last analysis cycle
cycle_period: 24                ##cycle period, in hours

time: '202107120000'

obs_time_steps: [0]
obs_time_scale: 0
state_time_steps: [0]
state_time_scale: 0

grid_def:
  type: 'topaz.v5'

state_def:
- name: 'ocean_velocity'
  model_src: 'topaz.v5'
  var_type: 'field'
  err_type: 'normal'
- name: 'ocean_temp'
  model_src: 'topaz.v5'
  var_type: 'field'
  err_type: 'normal'
- name: 'ocean_saln'
  model_src: 'topaz.v5'
  var_type: 'field'
  err_type: 'normal'
- name: 'ocean_layer_thick'
  model_src: 'topaz.v5'
  var_type: 'field'
  err_type: 'normal'
- name: 'ocean_mixl_depth'
  model_src: 'topaz.v5'
  var_type: 'field'
  err_type: 'normal'
- name: 'ocean_b_velocity'
  model_src: 'topaz.v5'
  var_type: 'field'
  err_type: 'normal'
- name: 'ocean_b_press'
  model_src: 'topaz.v5'
  var_type: 'field'
  err_type: 'normal'
- name: 'seaice_velocity'
  model_src: 'topaz.v5'
  var_type: 'field'
  err_type: 'normal'
- name: 'seaice_conc_ncat'
  model_src: 'topaz.v5'
  var_type: 'field'
  err_type: 'normal'
- name: 'seaice_volume_ncat'
  model_src: 'topaz.v5'
  var_type: 'field'
  err_type: 'normal'

obs_def:
# - name: 'ocean_temp'
#   dataset_src: 'topaz'
#   model_src: 'topaz.v5'
#   err:
#     type: 'normal'
#     std: 0.2
#   hroi: 2e5
#   vroi: inf
#   troi: 240
#   impact_on_state:
# - name: 'ocean_saln'
#   dataset_src: 'topaz'
#   model_src: 'topaz.v5'
#   err:
#     type: 'normal'
#     std: 5.
#   hroi: 2e5
#   vroi: inf
#   troi: 240
#   impact_on_state:
# - name: 'ocean_surf_temp'
#   dataset_src: 'topaz'
#   model_src: 'topaz.v5'
#   err:
#     type: 'normal'
#     std: 0.2
#   hroi: 2e5
#   vroi: inf
#   troi: 240
#   impact_on_state:
# - name: 'ocean_surf_height_anomaly'
#   dataset_src: 'topaz'
#   model_src: 'topaz.v5'
#   err:
#     type: 'normal'
#     std: 0.03
#   hroi: 2e5
#   vroi: inf
#   troi: 240
#   impact_on_state:
- name: 'seaice_conc'
  dataset_src: 'topaz'
  model_src: 'topaz.v5'
  err:
    type: 'normal'
    std: 0.1
  hroi: 2e5
  vroi: 10
  troi: 240
  impact_on_state:
    seaice_conc_ncat: 1
    seaice_volume_ncat: 1
# - name: 'seaice_thick'
#   dataset_src: 'topaz'
#   model_src: 'topaz.v5'
#   err:
#     type: 'normal'
#     std: 1.
#   hroi: 2e5
#   vroi: 10
#   troi: 240
#   impact_on_state:
#     seaice_conc_ncat: 0
#     seaice_volume_ncat: 0
# - name: 'seaice_drift'
#   dataset_src: 'topaz'
#   model_src: 'topaz.v5'
#   err:
#     type: 'normal'
#     std: 0.01
#   hroi: 2e5
#   vroi: 10
#   troi: 240
#   impact_on_state:

use_synthetic_obs: False

dataset_def:
  topaz:
    config_file: '/cluster/home/yingyue/code/NEDAS/dataset/topaz/default.yml'
    dataset_dir: '/cluster/work/users/yingyue/Data_TP5'

model_def:
  topaz.v5:
    config_file: '/cluster/home/yingyue/code/NEDAS/models/topaz/v5/default.yml'
    basedir: '/cluster/work/users/yingyue/TP5a0.06'
    model_env: '/cluster/home/yingyue/code/NEDAS/models/topaz/env/setup.src'
    nproc_per_run: 512  ##nproc for model.run
    nproc_per_util: 50  ##nproc for other utility funcs, model.preprocess etc.
    walltime: 3600     ##walltime in seconds
    restart_dt: 24
    forcing_dt: 6
    ens_run_type: scheduler
    use_job_array: False
    ens_init_dir: '/cluster/work/users/yingyue/26125/FORECAST'
    truth_dir: ''

perturb:
 - variable: ['atmos_surf_press', 'atmos_surf_velocity']
   model_src: 'topaz.v5'
   type: 'gaussian,press_wind_relate,scale_wind'
   amp: [316., 1.58]
   hcorr: [2.5e5, 2.5e5]
   tcorr: [48, 48]
 - variable: 'atmos_surf_temp'
   model_src: 'topaz.v5'
   type: 'gaussian'
   amp: 2
   hcorr: 2.5e5
   tcorr: 48
 - variable: 'atmos_precip'
   model_src: 'topaz.v5'
   type: 'gaussian,exp'
   amp: 0.5
   hcorr: 2.5e5
   tcorr: 48
   bounds: [0, inf]
 - variable: 'atmos_down_longwave'
   model_src: 'topaz.v5'
   type: 'gaussian,exp'
   amp: 0.045
   hcorr: 2.5e5
   tcorr: 48
 - variable: 'atmos_down_shortwave'
   model_src: 'topaz.v5'
   type: 'gaussian,exp'
   amp: 0.045
   hcorr: 2.5e5
   tcorr: 48

assim_mode: 'batch'
filter_type: 'ETKF'
covariance:
  type: 'ensemble-based'

inflation:
  type: ''
  adaptive: False
  coef: 1.0

localization:
  htype: 'GC'
  vtype: 'GC'
  ttype: 'GC'
  lookup_table: ''

diag:
- method: 'misc.convert_output'
  config_file: '/cluster/home/yingyue/code/NEDAS/diag/misc/convert_output/default.yml'
  model_src: 'topaz.v5'
  variables: ['seaice_conc_daily', 'seaice_thick_daily', 'seaice_velocity_daily', 'ocean_temp_daily']
  file: '/cluster/work/users/yingyue/data/TP5/{time:%Y}/{time:%m}/topaz5_local_mem{member:03}_b{time:%Y-%m-%d}T{time:%H}.nc'
- method: 'plot.ensemble_states'
  model_src: 'topaz.v5'
  variables: ['ocean_temp', 'ocean_saln', 'ocean_velocity', 'ocean_layer_thick', 'ocean_surf_height', 'seaice_velocity', 'seaice_conc', 'seaice_thick', 'atmos_surf_velocity', 'atmos_surf_temp', 'atmos_surf_press', 'atmos_precip']
  vmin: [-9,  3.5, -0.1,   0, -1, -0.1, 0, 0, -10, -20,  98000,    0]
  vmax: [20, 37.5,  0.1, 1e7,  1,  0.1, 1, 5,  10,  35, 104500, 2e-6]
  cmap: ['cmocean.thermal', 'cmocean.haline', 'bwr', 'cmocean.dense', 'cmocean.balance', 'bwr', 'cmocean.ice', 'viridis', 'bwr', 'cmocean.thermal', 'cmocean.dense', 'cmocean.rain']
  fig_size_x: 8
  fig_size_y: 8
  land_color: 'gray'
