work_dir: '/tmp/vort2d_test'

job_submit:
  ppn: 16

nproc: 1

nens: 20
run_assim: True
run_diag: False
debug: False      ##if true, output debug data/message

time_start: '200101010000'       ##start time of the experiment, format ccyymmddHHMM
time_end: '200101030000'         ##end time of the experiment
time_assim_start: '200101010300' ##start time of the first analysis cycle
time_assim_end: '200101022100'   ##end time of the last analysis cycle
cycle_period: 3                 ##cycle period, in hours

obs_time_steps: [0]
obs_time_scale: 0
state_time_steps: [0]
state_time_scale: 0

grid_def:
  type: 'vort2d'

state_def:
- name: 'velocity'
  model_src: 'vort2d'
  var_type: 'field'
  err_type: 'normal'

obs_def:
- name: 'velocity'
  dataset_src: 'vort2d'
  model_src: 'vort2d'
  nobs: 1000
  obs_window_min: -3
  obs_window_max: 0
  err:
    type: 'normal'
    std: 1.0
  hroi: 200000
  vroi: 10
  troi: 10
  impact_on_state:
     velocity: 1.0

use_synthetic_obs: True

dataset_def:
  vort2d:

model_def:
  vort2d:
    config_file: '/cluster/home/yingyue/code/NEDAS/models/vort2d/default.yml'
    ens_run_type: scheduler
    ens_init_dir: '/tmp/vort2d_test/init_run'
    truth_dir: '/tmp/vort2d_test/truth'

perturb:

assim_mode: 'batch'
filter_type: 'ETKF'

nscale: 1
scale_id: 0
decompose_obs: False
character_length: [10]
localize_scale_fac: [1]
obs_err_scale_fac: [1]

run_alignment: False
alignment:
  option: 'optical_flow'
  variable: 'velocity'
  nlevel: 3
  smoothness_weight: 1

inflation:
  type: 'posterior,relax'
  adaptive: True
  coef: 1.0

localization:
  htype: 'GC'
  vtype: 'GC'
  ttype: 'GC'
