host: 'betzy'   ##name of the host computer
nedas_dir: '/cluster/home/yingyue/code/NEDAS' ##where NEDAS code is placed
work_dir: '/cluster/work/users/yingyue/vort2d_testcase'   ##working directory for the experiment

nproc: 1        ##total number of processors
nproc_mem: 1    ##number of processor groups

nens: 20         ##ensemble size
run_assim: True   ##if true, run the assimilation steps

debug: False      ##if true, output debug data/message

time_start: '200101010000'       ##start time of the experiment, format ccyymmddHHMM
time_end: '200101030000'         ##end time of the experiment
time_assim_start: '200101010300' ##start time of the first analysis cycle
time_assim_end: '200101022100'   ##end time of the last analysis cycle
cycle_period: 3                 ##cycle period, in hours

time: '200101010000'
prev_time: '200101010000'
next_time: '200101010300'

obs_time_steps: [0]
obs_time_scale: 0
state_time_steps: [0]
state_time_scale: 0

grid_def:
  type: 'vort2d'

state_def:
- name: 'velocity'
  model_src: 'vort2d'
  var_type: 'field'
  err_type: 'normal'

obs_def:
- name: 'velocity'
  dataset_src: 'vort2d'
  dataset_dir: ''
  model_src: 'vort2d'
  nobs: 1000
  obs_window_min: -3
  obs_window_max: 0
  err:
    type: 'normal'
    std: 1.0
  hroi: 200000
  vroi: 10
  troi: 10
  impact_on_state:
    -velocity: 1.0

use_synthetic_obs: True

model_def:
  vort2d:
    config_file: '/cluster/home/yingyue/code/NEDAS/models/vort2d/default.yml'
    nproc_per_mem: 1    ##number of processors to run a forecast
    ens_run_type: scheduler
    truth_dir: '/cluster/work/users/yingyue/vort2d_testcase/truth'

assim_mode: 'batch'
filter_type: 'ETKF'
regress_type: 'linear'

inflation:
  type: 'posterior,relax'
  adaptive: True
  coef: 1.0

localization:
  htype: 'GC'
  vtype: 'GC'
  ttype: 'GC'
