work_dir: '/cluster/work/users/yingyue/qg'   ##working directory for the experiment
job_submit_cmd: '/cluster/home/yingyue/code/NEDAS/config/samples/job_submit_betzy.sh'

nproc: 16         ##total number of processors

nens: 20          ##ensemble size
run_assim: True   ##if true, run the assimilation steps
run_diag: False

debug: False      ##if true, output debug data/message

time_start: '202301010000'       ##start time of the experiment, format ccyymmddHHMM
time_end: '202302180000'         ##end time of the experiment
time_assim_start: '202301010000' ##start time of the first analysis cycle
time_assim_end: '202302180000'   ##end time of the last analysis cycle
cycle_period: 12                 ##cycle period, in hours

obs_time_steps: [0]
obs_time_scale: 0
state_time_steps: [0]
state_time_scale: 0

grid_def:
  type: 'custom'
  proj: '+proj=stere'
  xmin: 0
  xmax: 256
  ymin: 0
  ymax: 256
  dx: 1.0

state_def:
- name: 'streamfunc'
  model_src: 'qg'
  var_type: 'field'
  err_type: 'normal'

obs_def:
- name: 'streamfunc'
  dataset_src: 'qg'
  dataset_dir: ''
  model_src: 'qg'
  nobs: 3000
  obs_window_min: -6
  obs_window_max: 0
  err:
    type: 'normal'
    std: 0.2
  hroi: 100
  vroi: 5
  troi: 24
  impact_on_state:
  - streamfunc: 1.0

use_synthetic_obs: True

model_def:
  qg:
    config_file: '/cluster/home/yingyue/code/NEDAS/models/qg/default.yml'
    model_code_dir: '/cluster/home/yingyue/code/NEDAS/models/qg'
    nproc_per_run: 1    ##nproc for model.run
    nproc_per_util: 1   ##nproc for other utility funcs, model.preprocess, etc.
    walltime: 1000      ##walltime in seconds
    restart_dt: 12
    ens_run_type: scheduler
    ens_init_dir: '/cluster/work/users/yingyue/qg_ens_runs'
    truth_dir: '/cluster/work/users/yingyue/qg/truth'

perturb:
- variable: 'streamfunc'
  model_src: 'qg'
  type: 'gaussian'
  amp: 1
  hcorr: 10
  tcorr: 12

assim_mode: 'batch'
filter_type: 'ETKF'
regress_type: 'linear'

nscale: 1                    ## number of scale components
decompose_obs: False         ## if true, decompose observations as well
character_length: [16]       ## characteristic length (in grid coord unit) for each scale (large to small)
localize_scale_fac: [1]      ## scale factor for localization distances
obs_err_scale_fac: [1]       ## scale factor for observation error variances

run_alignment: True          ## if true, run alignment technique
alignment:
  variable: 'streamfunc'     ## which variable the alignment is based on
  nlevel: 5
  smoothness_weight: 1

inflation:
  type: 'posterior,relax'
  adaptive: True
  coef: 1.0

localization:
  htype: 'GC'
  vtype: 'GC'
  ttype: 'GC'

