mesh_file: small_arctic_10km.msh  ##mesh filename

ice_type: topaz
ocean_type: topaz
atmosphere_type: generic_ps
bathymetry_type: etopo
dynamics_type: bbm

timestep: 900

diffusivity_sss: 0
diffusivity_sst: 0
ocean_nudge_timeS: 1296000
ocean_nudge_timeT: 1296000
h_young_max: 0.23
alb_ice: 0.69
alb_sn: 0.88
albedoW: 0.07

time_relaxation_damage: 15.
compression_factor: 10000.0
cohesion: -1350000.0
substeps: 120
use_temperature_dependent_healing: True
ERA5_quad_drag_coef_air: 0.0017
quad_drag_coef_water: 0.0061625
Lemieux_basal_k1: 7.0
compaction_param: -25.0

start_from_restart: True
restart_input_path: restart
restart_type: extend
write_initial_restart: True
write_interval_restart: True
check_restart: True

datetime_in_filename: True
exporter_path: .
export_before_regrid: True
export_after_regrid: True

use_moorings: False
mooring_grid_type: regular
mooring_spacing: 3
mooring_variables: ['conc', 'thick', 'velocity', 'wind']

check_fields_fast: False

