##directories
nhc_root: NERSC-HYCOM-CICE
basedir: TP5a0.06
V: '2.2.98'
X: '04.1'
E: '041'
T: '05'
R: 'TP5a0.06'
nproc: 511
restart_dt: 168
output_dt: 24
forcing_dt: 6
ens_init_dir:
truth_dir:
forcing_file:
meanssh_file:

nproc_per_run: 512   ##batch size n*128, easier to divide up the compute nodes
nproc_per_util: 32
use_job_array: False
walltime: 3600
ens_run_type: scheduler
stagnant_log_timeout: 100

###model specific settings (blkdat)
idm: 800   ##longitudinal array size
jdm: 760   ##latitudinal array size
itest: -1   ##grid point where detailed diagnostics are desired
jtest: -1   ##grid point where detailed diagnostics are desired
kdm: 50   ##number of layers
nhybrd: 50   ## number of hybrid levels (0=all isopycnal)
nsigma: 0   ## number of sigma levels (nhybrd-nsigma z-levels)
dp00: 1.2   ##deep z-level spacing minimum thickness (m)
dp00x: 250.0   ##deep z-level spacing maximum thickness (m)
dp00f: 1.1   ##deep z-level spacing stretching factor (1.0=const.space)
ds00: 1.2   ##shallow z-level spacing minimum thickness (m)
ds00x: 75.0   ##shallow z-level spacing maximum thickness (m)
ds00f: 1.1   ##shallow z-level spacing stretching factor (1.0=const.space)
dp00i: 1.0   ##deep iso-pycnal spacing minimum thickness (m)
isotop: 6.0   ## shallowest depth for isopycnal layers (m, <0 from file)
saln0: 35.0   ##initial salinity value (psu), only used for iniflg<2
locsig: 0   ## locally-referenced pot. density for stability (0=F,1=T)
kapref: 0   ## thermobaric ref. state (-1=input,0=none,1,2,3=constant)
thflag: 0   ## reference pressure flag (0=Sigma-0, 2=Sigma-2, 4=Sigma-4)
thbase: 25.0   ## reference density (sigma units)
vsigma: 0   ## spacially varying isopycnal target densities (0=F,1=T)
sigma: [ 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 24.05, 25.72, 26.40, 26.90, 27.13, 27.19, 27.25, 27.29, 27.34, 27.42, 27.50, 27.56, 27.63, 27.66, 27.69, 27.72, 27.74, 27.76, 27.78, 27.80, 27.82, 27.85, 27.87, 27.90, 27.93, 27.95, 27.97, 27.99, 28.01, 28.02, 28.03, 28.04, 28.05, 28.06, 28.07, 28.08, 28.09, 28.10, 28.11, 28.12]  ##density (sigma units) for each layer 1-kdm
iniflg: 2   ## initial state flag (0=levl, 1=zonl, 2=clim)
jerlv0: 0   ## initial jerlov water type (1 to 5; 0 to use KPAR)
yrflag: 3   ## days in year flag (0=360, 1=366, 2=366J1, 3=actual)
sshflg: 0   ## diagnostic SSH flag (0=SSH,1=SSH&stericSSH)
dsurfq: 9999.0   ## number of days between model diagnostics at the surface
diagfq: 9999.0   ## number of days between model diagnostics
proffq: 0.0   ## number of days between model diagnostics at selected locs
tilefq: 0.0   ## number of days between model diagnostics on selected tiles
meanfq: 1.0   ## number of days between model diagnostics (time averaged)
rstrfq: 7.0   ## number of days between model restart output
bnstfq: -1.000   ## number of days between baro nesting archive input
nestfq: -1.000   ## number of days between 3-d nesting archive input
cplifq: -24   ## number of days (or time steps) between sea ice coupling
baclin: 300.0   ## baroclinic time step (seconds), int. divisor of 86400
batrop: 15.0   ## barotropic time step (seconds), int. div. of baclin/2
incflg: 0   ## incremental update flag (0=no, 1=yes, 2=full-velocity)
incstp: 100   ## no. timesteps for full update (1=direct insertion)
incupf: 1   ## number of days of incremental updating input
ra2fac: 0.125  ##weight for Robert-Asselin time filter
wbaro: 0.125   ##barotropic time smoothing weight
btrlfr: 1   ## leapfrog barotropic time step (0=F,1=T)
btrmas: 0   ## barotropic is mass conserving (0=F,1=T)
hybraf: 0   ## HYBGEN: Robert-Asselin flag   (0=F,1=T)
hybrlx: 8.0   ## HYBGEN: inverse relaxation coefficient (time steps)
hybiso: 0.01   ## HYBGEN: Use PCM if layer is within hybiso of target density
hybmap: 3   ## hybrid remapper flag (0=PCM, 1=PLM, 2=PPM)
hybflg: 0   ## hybrid generator flag (0=T&S, 1=th&S, 2=th&T)
advflg: 0   ## thermal advection flag (0=T&S, 1=th&S, 2=th&T)
advtyp: 2   ## scalar advection type (0=PCM,1=MPDATA,2=FCT2,4=FCT4)
momtyp: 2   ## momentum advection type (2=2nd order, 4=4th order)
slip: -1.0   ##+1 for free-slip, -1 for non-slip boundary conditions
visco2: 0.00   ## deformation-dependent Laplacian viscosity factor
visco4: 0.20   ## deformation-dependent biharmonic viscosity factor
facdf4: 0.0   ## speed-dependent biharmonic viscosity factor
veldf2: 0.00286   ## diffusion velocity (m/s) for Laplacian momentum dissip.
veldf4: -0.02   ## diffusion velocity (m/s) for biharmonic momentum dissip.
thkdf2: 0.00   ## diffusion velocity (m/s) for Laplacian thickness diffus.
thkdf4: -0.02   ## diffusion velocity (m/s) for biharmonic thickness diffus.
temdf2: 0.005   ## diffusion velocity (m/s) for Laplacian temp/saln diffus.
temdfc: 1.0   ## temp diffusion conservation (0.0,1.0 all dens,temp resp.)
vertmx: 2.e-5   ## diffusion velocity (m/s) for momentum at MICOM M.L.base
cbar: 0.1   ##rms flow speed (m/s) for linear bottom friction
cb: 2.e-3   ##coefficient of quadratic bottom friction
drglim: 0.0   ## limiter for explicit friction (1.0 none, 0.0 implicit)
thkbot: 10.0   ## thickness of bottom boundary layer (m)
sigjmp: 0.01   ## minimum density jump across interfaces (kg/m**3)
tmljmp: 0.2   ## equivalent temperature jump across mixed-layer (degC)
thkmls: 15.0   ## reference mixed-layer thickness for SSS relaxation (m)
thkmlt: 0.0   ## reference mixed-layer thickness for SST relaxation (m)
thkriv: 6.0   ## nominal thickness of river inflow (m)
thkcdw: 3.0   ## thickness for near-surface currents in ice-ocean stress (m)
thkfrz: 10.0   ## maximum thickness of near-surface freezing zone (m)
iceflg: 2   ## sea ice model flag (0=none,1=energy loan,2=coupled/esmf)
tfrz_0: 0.0   ## ENLN: ice melting point (degC) at S=0psu
tfrz_s: -0.054   ## ENLN: gradient of ice melting point (degC/psu)
frzifq: 0.25  ## e-folding time scale back to tfrz (days or -ve time steps) 
ticegr: 0.0   ## ENLN: temp. grad. inside ice (deg/m); =0 use surtmp
hicemn: 0.1   ## ENLN: minimum ice thickness (m)
hicemx: 10.0   ## ENLN: maximum ice thickness (m)
ishelf: 0   ## ice shelf flag    (0=none,1=ice shelf over ocean)
ntracr: 0   ## number of tracers (0=none,negative to initialize)
trcflg: 0   ## tracer flags (one digit per tr, most sig. replicated)
tsofrq: 64   ## number of time steps between anti-drift offset calcs
tofset: 0.0   ## temperature anti-drift offset (degC/century)
sofset: 0.0   ## salnity anti-drift offset (psu/century)
mlflag: 1   ## mixed layer flag (0=none,1=KPP,2-3=KT,4=PWP,5=MY,6=GISS)
pensol: 1   ## KT: activate penetrating solar rad. (0=F,1=T)
dtrate: 999.0   ## KT: maximum permitted m.l. detrainment rate (m/day)
thkmin: 19.2   ## KT/PWP: minimum mixed-layer thickness (m)
dypflg: 1   ## KT/PWP: diapycnal mixing flag (0=none, 1=KPP, 2=explicit)
mixfrq: 64   ## KT/PWP: number of time steps between diapycnal mix calcs
diapyc: 1.e-7   ## KT/PWP: diapycnal diffusivity x buoyancy freq. (m**2/s**2)
rigr: 0.25   ##PWP: critical gradient richardson number
ribc: 0.65   ##PWP: critical bulk richardson number
rinfty: 0.7   ## KPP: maximum gradient richardson number (shear inst.)
ricr: 0.3   ##KPP: critical bulk richardson number
bldmin: 0.0   ## KPP: minimum surface boundary layer thickness (m)
bldmax: 1200.0   ## K-PROF: maximum surface boundary layer thickness (m)
cekman: 0.7   ## KPP/KT: scale factor for Ekman depth
cmonob: 1.0   ## KPP: scale factor for Monin-Obukov depth
bblkpp: 1   ## KPP: activate bottom boundary layer (0=F,1=T)
shinst: 1   ## KPP: activate shear instability mixing (0=F,1=T)
dbdiff: 1   ## KPP: activate double diffusion mixing (0=F,1=T)
nonloc: 1   ## KPP: activate nonlocal b. layer mixing (0=F,1=T)
botdiw: 0   ## K_PROF: activate bot.enhan.int.wav mixing (0=F,1=T)
difout: 0   ## K-PROF: output visc/diff coffs in archive (0=F,1=T)
difsmo: 0   ## K-PROF: number of layers with horiz smooth diff coeffs
difm0: 50.e-4   ##KPP: max viscosity due to shear instability (m**2/s)
difs0: 50.e-4   ##KPP: max diffusivity due to shear instability (m**2/s)
difmiw: 3.e-5   ## KPP: background/internal wave viscosity (m**2/s)
difsiw: 1.e-5   ## KPP: background/internal wave diffusivity (m**2/s)
dsfmax: 10.e-4   ## KPP: salt fingering diffusivity factor (m**2/s)
rrho0: 1.9   ##KPP: salt fingering rp=(alpha*delT)/(beta*delS)
cs: 98.96   ##KPP: value for nonlocal flux term
cstar: 10.0   ##KPP: value for nonlocal flux term
cv: 0.0   ##KPP: buoyancy frequency ratio (0.0 to use a fn. of N)
c11: 5.0   ##KPP: value for turb velocity scale
hblflg: 2   ## KPP: b. layer interp. flag (0=const.,1=linear,2=quad.)
niter: 2   ##KPP: iterations for semi-implicit soln. (2 recomended)
langmr: 0   ## KPP:     activate Langmuir turb. factor    (0=F,1=T)
fltflg: 0   ## FLOATS: synthetic float flag (0=no; 1=yes)
nfladv: 4   ## FLOATS: advect every nfladv bacl. time steps (even, >=4)
nflsam: 0   ## FLOATS: output (0=every nfladv steps; >0=no. of days)
intpfl: 0   ## FLOATS: horiz. interp. (0=2nd order+n.n.; 1=n.n. only)
iturbv: 0   ## FLOATS: add horiz. turb. advection velocity (0=no; 1=yes)
ismpfl: 1   ## FLOATS: sample water properties at float (0=no; 1=yes)
tbvar: 4.63e-6   ##FLOATS: horizontal turb. vel. variance scale (m**2/s**2)
tdecri: 0.4   ## FLOATS: inverse decorrelation time scale (1/day)
lbflag: 2   ## lateral barotropic bndy flag (0=none, 1=port, 2=input)
tidflg: 0   ## TIDES: tidal forcing flag (0=none,1=open-bdy,2=bdy&body)
tidein: 0   ## TIDES: tide field input flag (0=no;1=yes;2=sal)
tidcon: '11111111'   ## TIDES: 1 digit per (Q1K2P1N2O1K1S2M2), 0=off,1=on
tidsal: 0.06   ## TIDES: scalar self attraction and loading factor (<0: file)
tiddrg: 0   ## TIDES: tidal drag flag (0=no;1=scalar;2=tensor)
thkdrg: 500.0   ## thickness of bottom boundary layer for tidal drag (m)
drgscl: 0.0   ## scale factor for tidal drag   (0.0 for no tidal drag)
tidgen: 1   ## TIDES: generic time (0=F,1=T)
tidrmp: 3.0   ## TIDES: ramp time (days)
tid_t0: 0.0   ## TIDES: origin for ramp time (model day)
clmflg: 12   ## climatology frequency flag (6=bimonthly, 12=monthly)
wndflg: 4   ## wind stress input flag (0=none,1=u/v-grid,2,3=p-grid,4,5=wnd10m)
ustflg: 2   ## ustar forcing flag (3=input,1,2=wndspd,4=stress)
flxflg: 6   ## thermal forcing flag (0=none,3=net-flux,1,2,4=sst-based,99=thermf_nersc)
empflg: 6   ## E-P forcing flag (0=none,3=net_E-P, 1,2,4=sst-bas_E)
dswflg: 0   ## diurnal shortwave flag (0=none,1=daily to diurnal corr.)
albflg: 2   ## ocean albedo      flag (0=none,1=const,2=L&Y)
sssflg: 1   ## SSS relaxation flag (0=none,1=clim)
lwflag: -1   ## longwave (SST) flag (0=none,1=clim,2=atmos)
sstflg: 0   ## SST relaxation flag (0=none,1=clim,2=atmos,3=observed)
icmflg: 0   ## ice mask flag (0=none,1=clim,2=atmos,3=obs/coupled)
prsbas: 0   ## msl pressure is input field + prsbas (Pa)
mslprf: 0   ## msl pressure forcing flag            (0=F,1=T)
stroff: 0   ## net stress offset flag               (0=F,1=T)
flxoff: 0   ## net flux offset flag (0=F,1=T)
flxsmo: 0   ## smooth surface fluxes (0=F,1=T)
relax: 0   ## activate lateral boundary nudging (0=F,1=T)
trcrlx: 0   ## activate lat. bound. tracer nudging (0=F,1=T)
priver: 1   ## rivers as a precipitation bogas (0=F,1=T)
epmass: 0   ## treat evap-precip as a mass exchange (0=F,1=T)
nmrsti: 0   ## 'restart'  Restart filename. Dot and date appended. Empty: use old hycom name.
nmrsto: 0   ## 'restart'  Restart filename. Dot and date appended. Empty: use old hycom name.
nmarcs: 0   ## '' Surface archive filename. Dot and date appended. Empty: use old hycom name.
nmarcv: 0   ## '' Full    archive filename. Dot and date appended. Empty: use old hycom name.
nmarcm: 0   ## '' Mean    archive filename. Dot and date appended. Empty: use old hycom name.
stdflg: 0   ## STOKES: add Stokes Drift velocities to kinematics and dynamics (0=F,1=T)
stdsur: 0   ## STOKES: add Stokes Drift Surface Stresses  to dnamics (0=F,1=T)
stdtau: 0   ## Remov from the tot wind stress the part lost to wave : (0=F,1=T)
stdwom: 0   ## Add wave-to-ocean momentum flux due to wave breaking  : (0=F,1=T)
stdbot: 0   ## STOKES: add Stokes Waves Field bottom friction drag (0=F,1=T)
stdarc: 0   ## STOKES: Stokes Drift Velocities in Archive (0=F,1=T)
altlng: 0   ## STOKES: Use alternative Lang def. from Kai et al (0=F,1=T)
nsdzi: 10   ## STOKES: number of interfaces in Stokes Drift input

##ports.input
nports: 2   ##'nports   ' = number of ports
kdport: [1, 2]   ##'kdport   ' = port orientation (1=N, 2=S, 3=E, 4=W)
ifport: [17, 345]   ##'ifport   ' = first i-index
ilport: [204, 694]   ##'ilport   ' = last  i-index (=ifport for east/west port)
jfport: [760, 2]   ##'jfport   ' = first j-index
jlport: [760, 2]   ##'jlport   ' = last  j-index (=jfport for north/south port)

##cice
cice_dt: 1200.0  ##cice model time step (seconds)
Nilayer  : 7   ## vertical layers for ice
Nslayer  : 1   ## vertical layers for snow

rhos     : 330.0   ## density of snow (kg/m^3)
rhoi     : 917.0   ## density of ice (kg/m^3)
rhow     : 1026.0  ## density of seawater (kg/m^3)
cp_air   : 1005.0  ## specific heat of air (J/kg/K)
##(Briegleb JGR 97 11475-11485  July 1992) cp_ice  := 2106.0   ## specific heat of fresh ice (J/kg/K)
cp_ocn   : 4218.0   ## specific heat of ocean (J/kg/K)
Lsub     : 2.835e6  ## latent heat, sublimation freshwater (J/kg)
Lvap     : 2.501e6  ## latent heat, vaporization freshwater (J/kg)
Lfresh   : 0.334e6  ## latent heat of melting fresh ice (j/kg)
depressT : 0.054

Tocnfrz  : -1.8    ## freezing temp of seawater (C),
Tffresh  : 273.15  ## freezing temp of fresh ice (K)
Tsmelt   : 0.0     ## melting temperature, snow top surface

saltmax  : 3.2     ## max salt in ice
min_salin: 0.1
hs_min   : 1.e-4     ## min snow thickness for computing zTsn (m)
msal     : 0.573
nsal     : 0.407

z_units: 'm'

ONEM: 9806.
MIN_SEAICE_CONC: 0.05
MAX_OCEAN_TEMP: 35.
MIN_OCEAN_SALN: 5.
MAX_OCEAN_SALN: 40.

thref: 1.e-3

aice_thresh: 1e-4
fice_thresh: 5e-4
hice_impact: 0
