! Generic quantities for NEDAS variables, one slot per variable (component).
! BEGIN DART PREPROCESS QUANTITY DEFINITIONS
!
!   QTY_NEDAS_01
!   QTY_NEDAS_02
!   QTY_NEDAS_03
!   QTY_NEDAS_04
!   QTY_NEDAS_05
!   QTY_NEDAS_06
!   QTY_NEDAS_07
!   QTY_NEDAS_08
!   QTY_NEDAS_09
!   QTY_NEDAS_10
!   QTY_NEDAS_11
!   QTY_NEDAS_12
!   QTY_NEDAS_13
!   QTY_NEDAS_14
!   QTY_NEDAS_15
!   QTY_NEDAS_16
!   QTY_NEDAS_17
!   QTY_NEDAS_18
!   QTY_NEDAS_19
!   QTY_NEDAS_20
!   QTY_NEDAS_21
!   QTY_NEDAS_22
!   QTY_NEDAS_23
!   QTY_NEDAS_24
!   QTY_NEDAS_25
!   QTY_NEDAS_26
!   QTY_NEDAS_27
!   QTY_NEDAS_28
!   QTY_NEDAS_29
!   QTY_NEDAS_30
!   QTY_NEDAS_31
!   QTY_NEDAS_32
!   QTY_NEDAS_33
!   QTY_NEDAS_34
!   QTY_NEDAS_35
!   QTY_NEDAS_36
!   QTY_NEDAS_37
!   QTY_NEDAS_38
!   QTY_NEDAS_39
!   QTY_NEDAS_40
!
! END DART PREPROCESS QUANTITY DEFINITIONS
