kmax: 127  ## max resolved wavenumber; spectral resolution
nz: 2  ## number of vertical layers

F: 100  ## f^2*L^2/[(2pi)^2g H_0]
beta: 16  ## beta_0*L^2/[(2pi)^2 U]

adapt_dt: False  ## if true, use adaptive time steps
dt: 0.00025  ## time step

psi_init_file: 'input'
psi_init_type: 'read'  ## initial condition input source: read/spectral_m/spectral_z/elliptical_vortex

initialize_energy: False ## if true, the input field will be normalized
e_o: 10  ## initial energy
k_o: 3  ## initial peak wavenumber
delk: 5  ## initial spread in wavenumber
m_o: 0  ## initial modal peak
z_o: 0  ## initial level of peak

strat_type: 'linear'  ## stratification type: linear/twolayer/exp/stc/read
deltc: 0.1  ## thermocline thickness

ubar_type: 'linear'  ## mean u type
delu: 0.1  ## ubar surf intens
uscale: 0.2  ## scale factor for u

use_topo: False  ## if true, include topography
topo_type: 'spectral'  ## topography type: gaussbump/spectral/xslope/yslope/read
k_o_topo: 10  ## peak posn for kspc hb
del_topo: 3  ## bump width in k or x

use_forcing: False  ## if true, use random markov forcing
norm_forcing: False  ## if true, normalize generation rate from random markov forcing
forc_coef: 0  ## forcing coefficient
forc_corr: 0  ## forcing correlation
kf_min: 1  ## min k^2 for forcing
kf_max: 3  ## max k^2 for forcing

filter_type: 'exp_cutoff'  ## types of filter:hyperviscous/exp_cutoff/none
filter_exp: 8  ## filter exponent
filt_tune: 1  ## filter coefficient
k_cut: 100  ## exp cutoff wavenumber
rho_slope: 0.001  ## linear slope for filter

bot_drag: 0.5  ## bottom drag coef
therm_drag: 0  ## thermal drag coef

idum: 0  ## random seed number

